import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# WRP Simulation: Lodewijkstraat (Statistical Verification)\n",
            "\n",
            "This notebook runs the Lodewijkstraat simulation with **Empirical Gamma Distributions** extracted from the client's Excel data. It executes multiple Monte Carlo replications (N=30) to compute robust 95% Confidence Intervals for system performance."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "%load_ext autoreload\n",
            "%autoreload 2\n",
            "\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "\n",
            "from Entity import CustomerItineraryGenerator\n",
            "from DSE import (\n",
            "    Environment, LocationType, QueueLocation, \n",
            "    ServiceLocation, VehicleSize, Location, ItineraryItem\n",
            ")\n",
            "\n",
            "# Apply seaborn theme for clean visualizations\n",
            "sns.set_theme(style=\"whitegrid\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 1. Define Realistic Samplers (From Data Lodewijkstraat.xlsx)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class Sampler:\n",
            "    def __init__(self, name, params, seed=None):\n",
            "        self.rng = np.random.default_rng(seed)\n",
            "        self._sampling_method = getattr(self.rng, name)\n",
            "        self.dist_params = params\n",
            "\n",
            "    def sample(self, size=None):\n",
            "        val = self._sampling_method(**self.dist_params, size=size)\n",
            "        return max(0.1, abs(float(np.squeeze(val))))\n",
            "\n",
            "def get_gamma_params(mean, stdev):\n",
            "    variance = stdev ** 2\n",
            "    shape = (mean ** 2) / variance\n",
            "    scale = variance / mean\n",
            "    return {\"shape\": shape, \"scale\": scale}\n",
            "\n",
            "# Data extracted from \"Data Lodewijkstraat.xlsx\"\n",
            "samplers = {\n",
            "    'entrance': Sampler('gamma', get_gamma_params(30, 12)),\n",
            "    'hall_big': Sampler('gamma', get_gamma_params(423, 270)),\n",
            "    'hall_small': Sampler('gamma', get_gamma_params(240, 150)),\n",
            "    'overflow_small': Sampler('gamma', get_gamma_params(180, 150)),\n",
            "    'dcdd': Sampler('gamma', get_gamma_params(331, 300)),\n",
            "    'green': Sampler('gamma', get_gamma_params(341, 260)),\n",
            "    'rest': Sampler('gamma', get_gamma_params(141, 36))\n",
            "}"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def generate_scheduled_customers(scale=1.0):\n",
            "    generator = CustomerItineraryGenerator()\n",
            "    dse_customers = []\n",
            "    \n",
            "    location_map = {\n",
            "        0: LocationType.MAIN_QUEUE, \n",
            "        1: LocationType.HALL_OVERFLOW, \n",
            "        2: LocationType.DCDD, \n",
            "        3: LocationType.GREEN,\n",
            "        4: LocationType.REST, \n",
            "        5: LocationType.EXIT\n",
            "    }\n",
            "\n",
            "    # Defined schedule: (start_sec, end_sec, rate_per_hour)\n",
            "    # 0 sec = 09:30 AM\n",
            "    schedule = [\n",
            "        (0,      1800,  10 * scale),\n",
            "        (1800,   4500,  100 * scale),\n",
            "        (4500,   7200,  40 * scale),\n",
            "        (7200,   12600, 100 * scale),\n",
            "        (12600,  19800, 100 * scale),\n",
            "        (19800,  25200, 80 * scale),\n",
            "        (25200,  27000, 50 * scale)\n",
            "    ]\n",
            "    \n",
            "    arrival_clock = 0.0\n",
            "    rng = np.random.default_rng()\n",
            "    \n",
            "    for start_time, end_time, rate_per_hour in schedule:\n",
            "        if rate_per_hour <= 0: continue\n",
            "        rate_per_sec = rate_per_hour / 3600.0\n",
            "        \n",
            "        if arrival_clock < start_time:\n",
            "            arrival_clock = start_time\n",
            "            \n",
            "        while True:\n",
            "            inter_arrival = rng.exponential(1.0 / rate_per_sec)\n",
            "            arrival_clock += inter_arrival\n",
            "            \n",
            "            if arrival_clock >= end_time:\n",
            "                # Rewind clock slightly to boundary so next bucket properly captures overflow\n",
            "                arrival_clock -= inter_arrival\n",
            "                break\n",
            "                \n",
            "            raw_itinerary = generator.Next()\n",
            "            v_size = VehicleSize.BIG if np.random.rand() < 0.47 else VehicleSize.SMALL\n",
            "            \n",
            "            dse_itinerary = []\n",
            "            for i, loc_int in enumerate(raw_itinerary):\n",
            "                loc_enum = location_map[loc_int]\n",
            "                \n",
            "                service_time = 0.0\n",
            "                if loc_enum == LocationType.HALL_OVERFLOW:\n",
            "                    service_time = samplers['hall_big'].sample() if v_size == VehicleSize.BIG else samplers['hall_small'].sample()\n",
            "                elif loc_enum == LocationType.DCDD:\n",
            "                    service_time = samplers['dcdd'].sample()\n",
            "                elif loc_enum == LocationType.GREEN:\n",
            "                    service_time = samplers['green'].sample()\n",
            "                elif loc_enum == LocationType.REST:\n",
            "                    service_time = samplers['rest'].sample()\n",
            "                    \n",
            "                item = ItineraryItem(location=loc_enum, service_time=service_time)\n",
            "                if i == 0:\n",
            "                    item.start_time = arrival_clock\n",
            "                dse_itinerary.append(item)\n",
            "                if i == 0:\n",
            "                    dse_itinerary.append(ItineraryItem(location=LocationType.HALL_QUEUE, service_time=0))\n",
            "                    \n",
            "            import DSE \n",
            "            dse_customers.append(DSE.Customer(dse_itinerary, v_size))\n",
            "            \n",
            "    return dse_customers\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 2. Network Configuration\n",
            "Connecting nodes ensuring prioritisation according to business rules."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def setup_environment(customers):\n",
            "    entrance = QueueLocation(LocationType.MAIN_QUEUE, maximum_capacity=99999)\n",
            "    hall_queue = QueueLocation(LocationType.HALL_QUEUE, maximum_capacity=14)\n",
            "    \n",
            "    hall_pairs = [[i, i+1] for i in range(0, 12, 2)]\n",
            "    hall_overflow = ServiceLocation(LocationType.HALL_OVERFLOW, max_capacity=12, single_bays=22, single_bay_pairs=hall_pairs)\n",
            "    \n",
            "    dcdd_pairs = [[0, 1], [2, 3], [4, 5]]\n",
            "    dcdd = ServiceLocation(LocationType.DCDD, max_capacity=7, single_bays=7, single_bay_pairs=dcdd_pairs)\n",
            "    \n",
            "    green_pairs = [[0, 1], [1, 2], [2, 3], [3, 4]]\n",
            "    green = ServiceLocation(LocationType.GREEN, max_capacity=5, single_bays=5, single_bay_pairs=green_pairs)\n",
            "    \n",
            "    rest_pairs = [[0, 1], [1, 2], [2, 3], [3, 4]]\n",
            "    rest = ServiceLocation(LocationType.REST, max_capacity=5, single_bays=5, single_bay_pairs=rest_pairs)\n",
            "    \n",
            "    exit_node = QueueLocation(LocationType.EXIT, maximum_capacity=999999)\n",
            "\n",
            "    entrance.connect(hall_queue)\n",
            "    hall_queue.connect(hall_overflow)\n",
            "    hall_queue.connect(dcdd)\n",
            "    hall_queue.connect(green)\n",
            "    hall_queue.connect(rest)\n",
            "    hall_queue.connect(exit_node)\n",
            "\n",
            "    dcdd.connect(rest)\n",
            "    green.connect(rest)\n",
            "    hall_overflow.connect(rest)\n",
            "    \n",
            "    hall_overflow.connect(dcdd)\n",
            "    \n",
            "    hall_overflow.connect(exit_node)\n",
            "    dcdd.connect(exit_node)\n",
            "    green.connect(exit_node)\n",
            "    rest.connect(exit_node)\n",
            "\n",
            "    locations_dict = {\n",
            "        LocationType.MAIN_QUEUE: entrance,\n",
            "        LocationType.HALL_QUEUE: hall_queue,\n",
            "        LocationType.HALL_OVERFLOW: hall_overflow,\n",
            "        LocationType.DCDD: dcdd,\n",
            "        LocationType.GREEN: green,\n",
            "        LocationType.REST: rest,\n",
            "        LocationType.EXIT: exit_node\n",
            "    }\n",
            "    \n",
            "    return Environment(customers, locations_dict, initial_time=0)"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 3. Simulation Replications (Statistical Batches)\n",
            "Generating N=30 runs for both Baseline and +20% scenario to get full statistical convergence."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def run_replications(scale=1.0, num_replications=30):\n",
            "    all_traces = []\n",
            "    all_turnarounds = []\n",
            "    \n",
            "    for rep in range(num_replications):\n",
            "        customers = generate_scheduled_customers(scale)\n",
            "        env = setup_environment(customers)\n",
            "        \n",
            "        # Run up to 35000s (~9.7 hours) to ensure all customers finish\n",
            "        env.run(end_time=35000)\n",
            "        \n",
            "        data = []\n",
            "        for i, c in enumerate(customers):\n",
            "            cid = getattr(c, 'id', i) \n",
            "            for item in c.itinerary:\n",
            "                data.append({\n",
            "                    'replication': rep,\n",
            "                    'customer_id': cid,\n",
            "                    'vehicle_size': c.vehicle_size.name,\n",
            "                    'location': item.location.name,\n",
            "                    'start_time': item.start_time,\n",
            "                    'end_time': item.end_time,\n",
            "                    'wait_time': item.time_waiting,\n",
            "                    'service_time': item.service_time\n",
            "                })\n",
            "                \n",
            "        df_rep = pd.DataFrame(data)\n",
            "        df_rep['queue_exit_time'] = df_rep['start_time'] + df_rep['wait_time']\n",
            "        all_traces.append(df_rep)\n",
            "        \n",
            "        sys_time = df_rep.groupby('customer_id').agg(\n",
            "            entry_time=('start_time', 'min'),\n",
            "            exit_time=('end_time', 'max')\n",
            "        )\n",
            "        sys_time['total_time'] = sys_time['exit_time'] - sys_time['entry_time']\n",
            "        sys_time['replication'] = rep\n",
            "        all_turnarounds.append(sys_time)\n",
            "        \n",
            "    return pd.concat(all_traces, ignore_index=True), pd.concat(all_turnarounds, ignore_index=True)\n",
            "\n",
            "print(\"Running 100 Monte Carlo Replications for Baseline Scheduled Arrivals...\")\n",
            "df_base, turn_base = run_replications(scale=1.0, num_replications=100)\n",
            "print(\"Finished Baseline.\")\n",
            "print(\"\\nRunning 100 Monte Carlo Replications for +20% Scenario Scheduled Arrivals...\")\n",
            "df_inc, turn_inc = run_replications(scale=1.2, num_replications=100)\n",
            "print(\"Finished +20% Scenario.\")\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### 4. Visualizations & Validations (With 95% Confidence Intervals)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def plot_statistical_wait_times(df, title):\n",
            "    df_filtered = df[df['location'] != 'EXIT'].copy()\n",
            "    # Convert seconds to minutes for easier readability\n",
            "    df_filtered['Wait Time (Mins)'] = df_filtered['wait_time'] / 60.0\n",
            "    df_filtered['Wait Type'] = df_filtered['service_time'].apply(\n",
            "        lambda x: 'Waiting in Queue' if x == 0 else 'Blocked (Downstream Full)'\n",
            "    )\n",
            "    \n",
            "    plt.figure(figsize=(12, 7))\n",
            "    sns.barplot(\n",
            "        data=df_filtered, \n",
            "        x='location', \n",
            "        y='Wait Time (Mins)', \n",
            "        hue='Wait Type', \n",
            "        dodge=False, \n",
            "        palette='magma',\n",
            "        errorbar=('ci', 95)\n",
            "    )\n",
            "    \n",
            "    plt.title(title, fontsize=14, fontweight='bold')\n",
            "    plt.ylabel('Average Wait/Blocked Time (Minutes)', fontsize=12)\n",
            "    plt.xlabel('Location', fontsize=12)\n",
            "    plt.xticks(rotation=45)\n",
            "    plt.legend(title='Bottleneck Reason', bbox_to_anchor=(1.05, 1), loc='upper left')\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "plot_statistical_wait_times(df_base, 'Baseline: Statistical Mean Wait Time By Node (95% CI)')\n",
            "plot_statistical_wait_times(df_inc, '+20% Scenario: Statistical Mean Wait Time By Node (95% CI)')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def plot_arrival_and_vehicles(df, title, color='skyblue'):\n",
            "    # Filter for first arrival node to calculate accurate simulation entrance times\n",
            "    arrivals = df[df['location'] == 'MAIN_QUEUE'].copy()\n",
            "    arrivals['Time of Day (Hours)'] = 9.5 + (arrivals['start_time'] / 3600.0)\n",
            "    \n",
            "    fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n",
            "    \n",
            "    # 1. Arrival Distribution (Explicit 1D bins to completely bypass the internal broadcast error)\n",
            "    explicit_bins = np.arange(9.0, 18.5, 0.5)\n",
            "    sns.histplot(data=arrivals, x='Time of Day (Hours)', bins=explicit_bins, ax=axes[0], color=color)\n",
            "    axes[0].set_title('Arrival Rate Histogram (Across Replications)', fontweight='bold')\n",
            "    axes[0].set_ylabel('Aggregated Total Arrivals')\n",
            "    axes[0].set_xticks(np.arange(9, 18, 1))\n",
            "    axes[0].set_xticklabels([f\"{int(h)}:00\" if h % 1 == 0 else f\"{int(h)}:30\" for h in np.arange(9, 18, 1)])\n",
            "    \n",
            "    # 2. Vehicle Ratio Pie Chart\n",
            "    counts = arrivals['vehicle_size'].value_counts()\n",
            "    axes[1].pie(counts, labels=counts.index, autopct='%1.1f%%', colors=sns.color_palette('pastel'), shadow=True, startangle=90)\n",
            "    axes[1].set_title('Vehicle Size Ratio', fontweight='bold')\n",
            "    \n",
            "    fig.suptitle(title, fontsize=16, fontweight='bold', y=1.05)\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "plot_arrival_and_vehicles(df_base, 'Baseline: Arrival Rates & Vehicle Ratio', color='teal')\n",
            "plot_arrival_and_vehicles(df_inc, '+20% Scenario: Arrival Rates & Vehicle Ratio', color='crimson')"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def plot_turnaround_times_kde(turn_base, turn_inc):\n",
            "    plt.figure(figsize=(12, 7))\n",
            "    \n",
            "    # Convert Turnaround Time to Minutes\n",
            "    turn_base = turn_base.copy()\n",
            "    turn_inc = turn_inc.copy()\n",
            "    turn_base['total_time_mins'] = turn_base['total_time'] / 60.0\n",
            "    turn_inc['total_time_mins'] = turn_inc['total_time'] / 60.0\n",
            "    \n",
            "    turn_base['Scenario'] = 'Baseline (605 cars)'\n",
            "    turn_inc['Scenario'] = '+20% (726 cars)'\n",
            "    \n",
            "    combined = pd.concat([turn_base, turn_inc])\n",
            "    \n",
            "    sns.kdeplot(data=combined, x='total_time_mins', hue='Scenario', fill=True, common_norm=False, palette='crest', alpha=0.5)\n",
            "    \n",
            "    plt.title(\"Turnaround Time Density (Aggregated across 30 Replications)\", fontsize=14, fontweight='bold')\n",
            "    plt.xlabel('Total Time spent in system (Minutes)', fontsize=12)\n",
            "    plt.ylabel('Density', fontsize=12)\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "plot_turnaround_times_kde(turn_base, turn_inc)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def plot_queue_progress_ci(df, title):\n",
            "    time_bins = np.arange(0, 35000, 60)\n",
            "    time_hours = 9.5 + (time_bins / 3600.0) \n",
            "    \n",
            "    locations = [loc for loc in df['location'].unique() if loc != 'EXIT']\n",
            "    records = []\n",
            "    \n",
            "    for rep in df['replication'].unique():\n",
            "        rep_df = df[df['replication'] == rep]\n",
            "        for loc in locations:\n",
            "            loc_df = rep_df[(rep_df['location'] == loc) & (rep_df['start_time'] < rep_df['end_time'])]\n",
            "            small_df = loc_df[loc_df['vehicle_size'] == 'SMALL']\n",
            "            big_df = loc_df[loc_df['vehicle_size'] == 'BIG']\n",
            "            \n",
            "            b_weight = 2 if loc not in ['MAIN_QUEUE', 'HALL_QUEUE'] else 1\n",
            "            \n",
            "            s_occ = np.zeros(len(time_bins))\n",
            "            if not small_df.empty:\n",
            "                s_arr = pd.DataFrame({'time': small_df['start_time'], 'change': 1})\n",
            "                s_dep = pd.DataFrame({'time': small_df['end_time'], 'change': -1})\n",
            "                s_ev = pd.concat([s_arr, s_dep]).sort_values(by=['time', 'change'], ascending=[True, False])\n",
            "                s_ev['occupancy'] = s_ev['change'].cumsum()\n",
            "                s_idxs = np.searchsorted(s_ev['time'].values, time_bins, side='right') - 1\n",
            "                s_occ = np.where(s_idxs >= 0, s_ev['occupancy'].values[s_idxs], 0)\n",
            "                \n",
            "            b_occ = np.zeros(len(time_bins))\n",
            "            if not big_df.empty:\n",
            "                b_arr = pd.DataFrame({'time': big_df['start_time'], 'change': b_weight})\n",
            "                b_dep = pd.DataFrame({'time': big_df['end_time'], 'change': -b_weight})\n",
            "                b_ev = pd.concat([b_arr, b_dep]).sort_values(by=['time', 'change'], ascending=[True, False])\n",
            "                b_ev['occupancy'] = b_ev['change'].cumsum()\n",
            "                b_idxs = np.searchsorted(b_ev['time'].values, time_bins, side='right') - 1\n",
            "                b_occ = np.where(b_idxs >= 0, b_ev['occupancy'].values[b_idxs], 0)\n",
            "                \n",
            "            tot_occ = s_occ + b_occ\n",
            "            \n",
            "            temp_tot = pd.DataFrame({'Time of Day (Hours)': time_hours, 'Occupancy': tot_occ, 'Type': 'Total Capacity Used'})\n",
            "            temp_tot['location'] = loc\n",
            "            temp_tot['replication'] = rep\n",
            "            records.append(temp_tot)\n",
            "            \n",
            "            temp_big = pd.DataFrame({'Time of Day (Hours)': time_hours, 'Occupancy': b_occ, 'Type': 'Capacity Used (BIG Cars)'})\n",
            "            temp_big['location'] = loc\n",
            "            temp_big['replication'] = rep\n",
            "            records.append(temp_big)\n",
            "            \n",
            "    progress_df = pd.concat(records, ignore_index=True)\n",
            "    \n",
            "    max_cap = {\n",
            "        'MAIN_QUEUE': None,\n",
            "        'HALL_QUEUE': 14,\n",
            "        'HALL_OVERFLOW': 12,\n",
            "        'DCDD': 7,\n",
            "        'GREEN': 5,\n",
            "        'REST': 5\n",
            "    }\n",
            "    \n",
            "    g = sns.FacetGrid(progress_df, col=\"location\", col_wrap=3, height=4, aspect=1.3, sharey=False)\n",
            "    g.map_dataframe(sns.lineplot, x='Time of Day (Hours)', y='Occupancy', hue='Type', errorbar=('ci', 95), linewidth=2, palette=['teal', 'orange'])\n",
            "    \n",
            "    for ax, loc_name in zip(g.axes.flatten(), g.col_names):\n",
            "        cap = max_cap.get(loc_name)\n",
            "        if cap is not None:\n",
            "            ax.axhline(cap, color='crimson', linestyle='--', linewidth=2, label=f'Max Capacity ({cap})')\n",
            "        ax.legend(loc='upper right')\n",
            "        ax.set_title(loc_name, fontweight='bold')\n",
            "        ax.set_xticks(np.arange(9, 19, 2))\n",
            "        ax.set_xticklabels([f\"{int(h)}:00\" if h % 1 == 0 else f\"{int(h)}:30\" for h in np.arange(9, 19, 2)])\n",
            "        \n",
            "    g.fig.suptitle(title, y=1.05, fontsize=16, fontweight='bold')\n",
            "    plt.tight_layout()\n",
            "    plt.show()\n",
            "\n",
            "print(\"Building Line plots (this takes a few seconds)...\")\n",
            "plot_queue_progress_ci(df_inc, '+20% Scenario: Capacity Occupancy mapped by Constraints')"
        ]
    }
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "cv",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.14.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open('/tmp/wrp2.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)
